---
  hosts:
    description: "List of Kafka brokers hosts:port for sender action."
    type: "string"
    default: "172.16.1.10:9092"
    required: true
  client_id:
    description: "Unique client ID to identify ourselves when sending"
    type: "string"
    default: "st2-kafka-producer"
    required: true
  tls_enable:
    description: "Use TLS for communication"
    type: "boolean"
    default: False
    required: false
  tls_ca_certificate:
    description: "CA certificate for TLS communication"
    type: "string"
    required: false
    secret: true
  tls_client_certificate:
    description: "Client certificate for TLS communication"
    type: "string"
    required: false
    secret: true
  tls_client_key:
    description: "Client private key for TLS communication"
    type: "string"
    required: false
    secret: true

  message_sensor:
    description: "Sensor specific settings"
    type: "object"
    required: false
    additionalProperties: true
    properties:
      hosts:
        description: "List of Kafka brokers hosts:port for sensor to connect to"
        type: "string"
        default: "172.16.1.10:9092"
        required: true
      topics:
        description: "List of topics for the sensor to subscribe to"
        type: "array"
        items:
          type: "string"
          default: "test"
          required: true
      group_id:
        description: "The sensors group ID"
        type: "string"
        default: "testgroupID"
        required: true
      client_id:
        description: "The sensors client ID"
        type: "string"
        default: "testclientID"
        required: true

  gcp_message_sensor:
    description: "GCP sensor specific settings"
    type: "object"
    required: false
    additionalProperties: true
    properties:
      hosts:
        description: "List of Kafka brokers hosts:port for sensor to connect to"
        type: "string"
        default: "172.16.1.10:9092"
        required: true
      topics:
        description: "List of base64 encoded topics for the sensor to subscribe to"
        type: "array"
        items:
          type: "string"
          default: "test"
          required: true
      group_id:
        description: "The sensors group ID"
        type: "string"
        default: "st2gcpgroup"
        required: true
      client_id:
        description: "The sensors client ID"
        type: "string"
        default: "st2gcpclient"
        required: true
